# Generated by Django 3.0.4 on 2020-04-07 22:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkillDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('work_exp', models.CharField(max_length=100)),
                ('expertise', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 22, 38, 9, 471427, tzinfo=utc))),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dateofbirth', models.DateField(max_length=15)),
                ('gender', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('add_line1', models.CharField(max_length=300)),
                ('add_line2', models.CharField(blank=True, max_length=300, null=True)),
                ('add_line3', models.CharField(blank=True, max_length=300, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('adhaar', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 22, 38, 9, 469429, tzinfo=utc))),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEduDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification1', models.CharField(max_length=100)),
                ('qual1_stream', models.CharField(max_length=100)),
                ('qual1_sub', models.CharField(max_length=100)),
                ('qual1_pass_year', models.DateField(max_length=15)),
                ('qual1_college', models.CharField(max_length=100)),
                ('qualification2', models.CharField(max_length=100)),
                ('qual2_stream', models.CharField(max_length=100)),
                ('qual2_sub', models.CharField(max_length=100)),
                ('qual2_pass_year', models.DateField(max_length=15)),
                ('qual2_college', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 4, 7, 22, 38, 9, 470428, tzinfo=utc))),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='profilepic/')),
                ('dob', models.DateField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
