# Generated by Django 3.0.4 on 2020-04-08 10:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200408_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredudetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 10, 21, 19, 702198, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 10, 21, 19, 701199, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userskilldetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 10, 21, 19, 703197, tzinfo=utc)),
        ),
    ]
