# Generated by Django 3.0.4 on 2020-04-08 18:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200408_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='dateofbirth',
            new_name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 18, 17, 44, 336636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qual1_college',
            field=models.CharField(blank=True, max_length=100, verbose_name='College/University'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qual1_pass_year',
            field=models.DateField(blank=True, max_length=15, verbose_name='Year of Pass'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qual1_stream',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Certification', 'Certification'), ('Special Course', 'Special Course')], max_length=100, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qual1_sub',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qual2_college',
            field=models.CharField(blank=True, max_length=100, verbose_name='College/University'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qual2_pass_year',
            field=models.DateField(blank=True, max_length=15, verbose_name='Year of Pass'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qual2_stream',
            field=models.CharField(blank=True, choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Certification', 'Certification'), ('Special Course', 'Special Course')], max_length=100, verbose_name='Stream'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qual2_sub',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qualification1',
            field=models.CharField(choices=[('Mba', 'Mba'), ('btech', 'B.tech'), ('mtech', 'M.tech'), ('bsc', 'B.Sc'), ('msc', 'M.Sc'), ('bca', 'B.Ca'), ('mca', 'M.Ca'), ('bbm', 'BBM'), ('BBA', 'BBA'), ('ttm', 'TTM'), ('mttm', 'MTTM'), ('ba', 'B.A'), ('ma', 'M.A'), ('polytechnic', 'Poly Technic (3 Year)'), ('iti one year', 'ITI (1 Year)'), ('iti 6 month', 'ITI (6 Month)'), ('iti 2 year', 'ITI (2 Year)'), ('phd', 'Ph.D'), ('Mphil', 'M.phil'), ('plus2', 'Plus Two'), ('sslc', 'SSLC'), ('7std', '7 Standerd'), ('below7', 'Below 7 Standerd'), ('Others', 'Others')], max_length=100, verbose_name='Highest Qualification'),
        ),
        migrations.AlterField(
            model_name='useredudetails',
            name='qualification2',
            field=models.CharField(blank=True, choices=[('Mba', 'Mba'), ('btech', 'B.tech'), ('mtech', 'M.tech'), ('bsc', 'B.Sc'), ('msc', 'M.Sc'), ('bca', 'B.Ca'), ('mca', 'M.Ca'), ('bbm', 'BBM'), ('BBA', 'BBA'), ('ttm', 'TTM'), ('mttm', 'MTTM'), ('ba', 'B.A'), ('ma', 'M.A'), ('polytechnic', 'Poly Technic (3 Year)'), ('iti one year', 'ITI (1 Year)'), ('iti 6 month', 'ITI (6 Month)'), ('iti 2 year', 'ITI (2 Year)'), ('phd', 'Ph.D'), ('Mphil', 'M.phil'), ('plus2', 'Plus Two'), ('sslc', 'SSLC'), ('7std', '7 Standerd'), ('below7', 'Below 7 Standerd'), ('Others', 'Others')], max_length=100, verbose_name='Secondary Qualification'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='add_line1',
            field=models.CharField(max_length=300, verbose_name='House name/number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='add_line2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Locality and Villege'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='add_line3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='District and State'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='adhaar',
            field=models.CharField(blank=True, max_length=100, verbose_name='ADHAAR Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='blood_group',
            field=models.CharField(choices=[('O+ve', 'O+ve'), ('O-ve', 'O-ve'), ('A+ve', 'A+ve'), ('A-ve', 'A-vve'), ('B+ve', 'B+ve'), ('B-ve', 'B-ve'), ('AB+ve', 'AB+ve'), ('AB-ve', 'AB-ve')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 18, 17, 44, 335637, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Government Employee', 'Government Employee'), ('Engineer', 'Engineer'), ('Doctor', 'Doctor'), ('Accountant', 'Accountant'), ('Office Assistant', 'Office Assistant'), ('Sales Man', 'Sales Man'), ('Own Business', 'Own Business'), ('Painter', 'Painter'), ('Welder/Wiring', 'Welder/Wiring'), ('Drughman', 'Drughman'), ('Office Boy', 'Office Boy'), ('Others', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userskilldetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 18, 17, 44, 336636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userskilldetails',
            name='work_exp',
            field=models.CharField(max_length=100, verbose_name='Total Work Experience'),
        ),
    ]
