# Generated by Django 3.0.4 on 2020-04-09 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20200409_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useredudetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 2, 23, 54, 332647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 2, 23, 54, 331647, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userskilldetails',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 2, 23, 54, 333646, tzinfo=utc)),
        ),
    ]
